(function(g){var window=this;'use strict';var Qgb=function(a){g.T.call(this,{G:"div",N:"ytp-inline-preview-ui"});this.Vf=!1;this.player=a;this.S(a,"onStateChange",this.XO);this.S(a,"videodatachange",this.lw);this.S(a,"onInlinePreviewModeChange",this.H3);this.lf=new g.oo(this.Av,null,this);g.D(this,this.lf)},b6=function(a){g.aS.call(this,a);
this.j=new Qgb(this.player);g.D(this,this.j);this.j.hide();g.hR(this.player,this.j.element,4);if(a.isInline()){this.load();var b=a.getRootNode();g.zo(b,["ytp-inline-preview-mode","ytp-no-contextmenu"]);this.player.T().K("web_inline_player_disable_scrubbing")&&g.Co(a.getRootNode(),"ytp-inline-preview-mode-no-scrubbing",!0)}};
g.v(Qgb,g.T);g.k=Qgb.prototype;
g.k.cM=function(){this.tooltip=new g.BV(this.player,this);g.D(this,this.tooltip);g.hR(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.Rc=new g.VS(this.player);g.D(this,this.Rc);this.Uj=new g.T({G:"div",Ia:["ytp-inline-preview-scrim"]});g.D(this,this.Uj);this.Uj.Da(this.element);this.S(this.Uj.element,"click",this.PG);this.tj=new g.uV(this.player,this,300);g.D(this,this.tj);this.tj.Da(this.Uj.element);this.controls=new g.T({G:"div",N:"ytp-inline-preview-controls"});g.D(this,this.controls);
this.controls.Da(this.element);var a=new g.AU(this.player,this,this.player.T().K("kevlar_simp_remove_min_width_for_mute_button"));g.D(this,a);a.Da(this.controls.element);a=new g.sV(this.player,this);g.D(this,a);a.Da(this.controls.element);this.Jc=new g.HU(this.player,this);g.D(this,this.Jc);g.hR(this.player,this.Jc.element,4);this.S(this.player,"appresize",this.Eb);this.S(this.player,"fullscreentoggled",this.Eb);this.Eb()};
g.k.show=function(){g.po(this.lf);this.Vf||(this.cM(),this.Vf=!0);0!==this.player.getPlayerState()&&g.T.prototype.show.call(this);this.Jc.show();this.player.Na("onInlinePreviewUiReady")};
g.k.hide=function(){this.lf.stop();g.T.prototype.hide.call(this);this.player.isInline()||this.Vf&&this.Jc.hide()};
g.k.ra=function(){g.T.prototype.ra.call(this)};
g.k.PG=function(a){a.target===this.Uj.element&&this.player.Na("onExpandInlinePreview",a)};
g.k.H3=function(){g.Co(this.player.getRootNode(),"ytp-inline-preview-mode",this.player.isInline())};
g.k.Ie=function(){this.Jc.xc();this.tj.xc()};
g.k.Av=function(){this.Ie();g.po(this.lf)};
g.k.Eb=function(){g.UU(this.Jc,0,this.player.ib().getPlayerSize().width,!1);g.IU(this.Jc)};
g.k.XO=function(a){this.player.isInline()&&(0===a?this.hide():this.show())};
g.k.lw=function(a,b){if(this.player.isInline()){g.Co(this.player.getRootNode(),"ytp-show-inline-preview-audio-controls",b.JI);var c,d,e;a=!(null==(e=null==(c=b.getPlayerResponse())?void 0:null==(d=c.playerConfig)?void 0:d.inlinePlaybackConfig)||!e.showScrubbingControls);g.Co(this.player.getRootNode(),"ytp-hide-inline-preview-progress-bar",!a)}};
g.k.Cc=function(){return this.tooltip};
g.k.og=function(){return!1};
g.k.kh=function(){return!1};
g.k.Rb=function(){return!1};
g.k.Ll=function(){return!1};
g.k.FD=function(){};
g.k.Qp=function(){};
g.k.Ux=function(){};
g.k.Im=function(){return null};
g.k.CF=function(){return null};
g.k.FF=function(){return new g.je(0,0)};
g.k.NB=function(){return null};
g.k.Ak=function(){return new g.Gl(0,0,0,0)};
g.k.handleGlobalKeyDown=function(){return!1};
g.k.handleGlobalKeyUp=function(){return!1};
g.k.Lv=function(a,b,c,d,e){var f=d=0,h=0,l=g.$l(a);if(b){c=g.xo(b,"ytp-mute-button");var m=g.xo(b,"ytp-subtitles-button"),n=g.Sl(b,this.element);b=g.$l(b);d=n.y+40;if(m||c)h=n.x-l.width+b.width}else h=c-l.width/2,f=35;b=this.player.ib().getPlayerSize().width;h=g.de(h,0,b-l.width);d?(a.style.top=d+(e||0)+"px",a.style.bottom=""):(a.style.top="",a.style.bottom=f+"px");a.style.left=h+"px"};
g.k.showControls=function(){};
g.k.vp=function(){};
g.k.Fl=function(){return!1};
g.k.GD=function(){};
g.k.Gz=function(){};
g.k.Rq=function(){};
g.k.Qq=function(){};
g.k.KE=function(){};
g.k.Pr=function(){};g.v(b6,g.aS);b6.prototype.Tk=function(){return!1};
b6.prototype.load=function(){this.player.hideControls();this.j.show()};
b6.prototype.unload=function(){this.player.showControls();this.j.hide()};g.$R("inline_preview",b6);})(_yt_player);
